from enum import Enum

class Currency(Enum):
    USD = "USD"
    EUR = "EUR"
    GBP = "GBP"
    JPY = "JPY"
    AUD = "AUD"
    CAD = "CAD"
    CHF = "CHF"  
    NZD = "NZD"
    SEK = "SEK"
    NOK = "NOK"
    DKK = "DKK"
    SGD = "SGD"
    HKD = "HKD"
    ZAR = "ZAR"
    INR = "INR"
    CNY = "CNY"
    KRW = "KRW"
    MXN = "MXN"
    BRL = "BRL"
    RUB = "RUB"
    TRY = "TRY"
    PLN = "PLN"
    THB = "THB"
    IDR = "IDR"
    MYR = "MYR"
    PHP = "PHP"
    VND = "VND"
    TWD = "TWD"
    SAR = "SAR"
    AED = "AED"
    ILS = "ILS"
    HUF = "HUF"
    CZK = "CZK"
    CLP = "CLP"
    COP = "COP"
    PEN = "PEN"
    ARS = "ARS"
    UYU = "UYU"
    BGN = "BGN"
    RON = "RON"
    HRK = "HRK"
    ISK = "ISK"
    KZT = "KZT"
    NGN = "NGN"
    EGP = "EGP"
    PKR = "PKR"
    LKR = "LKR"
    BDT = "BDT"
    KES = "KES"
    GHS = "GHS"
    TZS = "TZS"
    UGX = "UGX"
    MAD = "MAD"
    DZD = "DZD"
    QAR = "QAR"
    OMR = "OMR"
    KWD = "KWD"
    BHD = "BHD"
    JOD = "JOD"
    LBP = "LBP"
    IRR = "IRR"
    IQD = "IQD"
    # ...additional currencies can be added as needed...

    def __str__(self):
        return self.value
